# Generated by Django 3.2.14 on 2022-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_rename_remaining_invitation_membership_remaining_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Pubilc circles are listed in the main page so everyone know about their existence'),
        ),
    ]
